#!/bin/bash
# embed_assets.sh — Convert asset files to C byte arrays for embedding in the binary.
# Usage: ./scripts/embed_assets.sh [output_dir]
#   output_dir defaults to build/embedded
#
# Uses a tiny C helper (bin2c) instead of xxd, so no external tools needed.

set -euo pipefail

OUTDIR="${1:-build/embedded}"
mkdir -p "$OUTDIR"

# ---- Build the bin2c helper if needed ----
BIN2C="$OUTDIR/bin2c"
if [[ ! -x "$BIN2C" ]]; then
    cat > "$OUTDIR/bin2c.c" <<'BIN2C_SRC'
/* bin2c — convert a binary file to a C array */
#include <stdio.h>
#include <stdlib.h>
int main(int argc, char **argv) {
    if (argc < 3) { fprintf(stderr, "usage: bin2c <varname> <file> [--null-term]\n"); return 1; }
    const char *varname = argv[1];
    const char *path = argv[2];
    int null_term = (argc > 3 && strcmp(argv[3], "--null-term") == 0);
    FILE *f = fopen(path, "rb");
    if (!f) { perror(path); return 1; }
    fseek(f, 0, SEEK_END);
    long len = ftell(f);
    fseek(f, 0, SEEK_SET);
    unsigned char *buf = malloc(len);
    if (!buf) { fclose(f); return 1; }
    fread(buf, 1, len, f);
    fclose(f);
    long total = null_term ? len + 1 : len;
    printf("unsigned char %s[] = {\n", varname);
    for (long i = 0; i < len; i++) {
        if (i % 16 == 0) printf("  ");
        printf("0x%02x,", buf[i]);
        if (i % 16 == 15) printf("\n");
    }
    if (null_term) {
        if (len % 16 == 0) printf("  ");
        printf("0x00,");
    }
    printf("\n};\nunsigned int %s_len = %ld;\n", varname, total);
    free(buf);
    return 0;
}
BIN2C_SRC
    gcc -O2 -o "$BIN2C" "$OUTDIR/bin2c.c" -include string.h
    echo "Built bin2c helper"
fi

# ---- Asset list ----
ASSETS=(
    assets/cards_spritesheet.png
    assets/card_back.png
    assets/sprites-temp/redjoker-final.png
    assets/sprites-temp/blackjoker-final.png
    assets/sprites-temp/shadowqueen-final.png
    assets/sprites-temp/martyr-final.png
    assets/sprites-temp/gatherer-final.png
    assets/sprites-temp/rogue-final.png
    assets/sprites-temp/pendulum-final.png
    assets/sprites-temp/duel-final.png
    assets/sprites-temp/fog-final.png
    assets/sprites-temp/mirror-final.png
    assets/sprites-temp/roulette-final.png
    assets/sprites-temp/trap-final.png
    assets/sprites-temp/shield-final.png
    assets/sprites-temp/curse-final.png
    assets/sprites-temp/anchor-final.png
    assets/sprites-temp/crown-final.png
    assets/sprites-temp/parasite-final.png
    assets/sprites-temp/bounty-final.png
    assets/sprites-temp/inversion-final.png
    assets/sprites-temp/binding-final.png
    assets/sprites-temp/joker-final.png
    assets/fonts/Lora-VariableFont_wght.ttf
    assets/music/background.ogg
    assets/sounds/card-play.ogg
    assets/sounds/card-deal.ogg
    assets/shaders/fog.fs
    assets/defs/contracts.json
    assets/defs/transmutations.json
)

# Extensions that need null termination (used as C strings)
NULL_TERM_EXTS=("fs" "json")

needs_null_term() {
    local ext="${1##*.}"
    for e in "${NULL_TERM_EXTS[@]}"; do
        [[ "$ext" == "$e" ]] && return 0
    done
    return 1
}

# Sanitize path to valid C identifier
to_cname() {
    echo "$1" | sed 's/[^a-zA-Z0-9]/_/g'
}

HEADER="$OUTDIR/embedded_assets.h"

cat > "$HEADER" <<'HEOF'
/* Auto-generated by scripts/embed_assets.sh — do not edit */
#ifndef EMBEDDED_ASSETS_H
#define EMBEDDED_ASSETS_H

HEOF

for asset in "${ASSETS[@]}"; do
    if [[ ! -f "$asset" ]]; then
        echo "WARNING: asset not found, skipping: $asset" >&2
        continue
    fi

    cname=$(to_cname "$asset")
    outfile="$OUTDIR/${cname}.c"

    extra_flag=""
    if needs_null_term "$asset"; then
        extra_flag="--null-term"
    fi

    "$BIN2C" "$cname" "$asset" $extra_flag > "$outfile"

    # Get the size for the #define
    filesize=$(wc -c < "$asset")
    if needs_null_term "$asset"; then
        filesize=$((filesize + 1))
    fi

    echo "extern unsigned char ${cname}[];" >> "$HEADER"
    echo "extern unsigned int ${cname}_len;" >> "$HEADER"
    echo "#define ${cname}_SIZE ${filesize}" >> "$HEADER"

    echo "  embedded: $asset -> $outfile"
done

cat >> "$HEADER" <<'HEOF'

#endif /* EMBEDDED_ASSETS_H */
HEOF

echo "Done. Generated $(ls "$OUTDIR"/*.c 2>/dev/null | wc -l) asset .c files + header in $OUTDIR/"
